version: '3.3'
services:
  web:
    container_name: GIBZMensaAPI
    build: .
    ports:
      - '8080:8080'
    restart: unless-stopped
    env_file:
      - stack.env
    healthcheck:
      test: ['CMD', 'node', '/app/services/healthcheck.js']
      interval: 1m
      timeout: 10s
      retries: 0

