version: "3.3"
services:
  web:
    container_name: GIBZMensaAPI
    volumes:
      - ./archive:/app/archive
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'node', '/app/healthcheck']
      interval: 1m30s
      timeout: 10s
      retries: 3