name: GIBZMensaAPI Docker Image CI

on:
  push:
    paths:
    - 'GIBZMensaAPI/**'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: cd ./GIBZMensaAPI && docker build . --file Dockerfile --tag gibzmensaapi:$(date +%s)
