name: GIBZMensaAPI Docker Image CI

on:
  push:
    paths:
      - 'GIBZMensaAPI/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: cd ./GIBZMensaAPI && docker build . --file Dockerfile --tag gibzmensaapi:$(date +%s) 
      
      - name: Sleep for 30 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'
          
      - uses: actions/checkout@v2    
      - name: show running container
        run: docker ps 
